# settings
MAX_GENERATIONS = 6000
POPULATION_N = 100
TOURNAMENT_N = 3
ELITARISM = False
ELITARISM_N = 3
MAX_PROGRAM_STEPS = 500

# consts
SELECTION_TOURNAMENT = 'tournament'
SELECTION_ROULETTE = 'roulette'
INST_INCREMENT = 0
INST_DECREMENT = 1
INST_JUMP = 2
INST_OUTPUT = 3
